// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjdactclvvzvumiwhjoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZGFjdGNsdnZ6dnVtaXdoam9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDkyMzMsImV4cCI6MjA2MjUyNTIzM30.0ZFuH1f7kH4Hx7PiaINPzlntwo_GtNt6ojtY1paSotI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);